language: python

env:
  global:
    # Doctr deploy key for streamlink/streamlink.github.io
    - secure: "e9rxQKoEqdJvk8l66qqpBtYN8uhnizwynCzAGTLb6q1wx7PA8V9zGqByMTBKEo+/BnfRTTxahcxHPu21qujLxvL6cbYraDBYSLJj06gQgIFnAueXbtHb/9Yjhdzlvz9jLwYA2S2LgZInor2FfduEIQlSivSlKSLIyO+JRh/1pa005+Gndx0DHMrFMdFO2+YisZksJxwpXgCwIqa4d4rLkLjg9p4a7E713CcDz1OhUNNyA2oGe8SMm96oq9z2O5CJrQ6E2weKflqu+LEITJylC3Pkz5klp9XK1BsQdA8J5aD5FdIxQIdam9Xjg03V5ww71RIHGSvKcOPu1sHpkpVuW6gc35Texk3M2Bl6OSKes2k49RmegTg/qhh16w/en8hm5Knymrkwq0/KPInjvOjg6d2g5781Mkr68cXGxI7PFb6on7LG5O0R6azrhJx5BAnUsfEb5E+CJ/c75os5fe/XDCcxNkCyM5uVlUeBRvKdr+Cq5CfCUm6x1EkxYf6E982fUcXnHWn6ofrW4wz+FRrtdYOh2GNtHq6SNcRpZvSN1am4Ztu3xTtT8kxne7ECqis9SFLIbPN1YI2b2d9nkE9W9xZu7eK9OpIb4f/wJtLJRp8+CWsQ2SN8milSvOYiK9XqvRlr+lW1hlLY27m492lKX+s6hYJ+7HljCJTJ9EXihnI="

matrix:
  include:
  - python: '2.7'
  - python: '3.4'
  - python: '3.5'
    env: BUILD_DOCS=yes BUILD_INSTALLER=yes STREAMLINK_INSTALLER_DIST_DIR=$TRAVIS_BUILD_DIR/dist/nsis
  - python: '3.6'
  - python: '3.7-dev'
  allow_failures:
  - python: '2.6'
  - python: '3.7-dev'

before_install:
  - pip install --disable-pip-version-check --upgrade pip setuptools
  - pip install -r dev-requirements.txt
  - pip install pycountry
  - if [[ $BUILD_DOCS == 'yes' ]]; then
      pip install -r docs-requirements.txt;
      pip install doctr;
    fi

install:
  - pip install -e .

script:
  - pytest --cov
  # test building the docs
  - if [[ $BUILD_DOCS == 'yes' ]]; then make --directory=docs html; fi
  - if [[ $BUILD_INSTALLER == 'yes' ]]; then ./script/makeinstaller.sh; fi

after_success:
  - set -e
  # latest version - push docs for master
  - if [[ $BUILD_DOCS == 'yes' && $TRAVIS_REPO_SLUG == 'streamlink/streamlink' ]]; then doctr deploy latest; fi
  # stable version - push docs for tags
  - if [[ $BUILD_DOCS == 'yes' && $TRAVIS_REPO_SLUG == 'streamlink/streamlink' && -n "$TRAVIS_TAG" ]]; then doctr deploy .; fi
  - codecov

addons:
  apt:
    packages:
    - nsis

before_deploy:
  - ./script/bintrayconfig.sh

deploy:
  - provider: releases
    api_key: "${RELEASES_API_KEY}"
    file: "${STREAMLINK_INSTALLER_DIST_DIR}/streamlink-${TRAVIS_TAG}.exe"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_INSTALLER = yes
  - provider: script
    script: python script/github_releases.py
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_INSTALLER == yes
  - provider: bintray
    file: build/bintray-nightly.json
    user: "${BINTRAY_USER}"
    key: "${BINTRAY_KEY}"
    skip_cleanup: true
    on:
      branch: master
      condition: $BUILD_INSTALLER == yes && $TRAVIS_EVENT_TYPE == cron

after_deploy:
  - if [[ "$BUILD_INSTALLER" == 'yes' && "$TRAVIS_EVENT_TYPE" == 'cron' ]]; then ./script/bintrayupdate.sh; fi

doctr:
  build-tags: True
  deploy-repo: streamlink/streamlink.github.io
  key-path: doctr_deploy_key.enc
  require-master: True
